[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pyright]
include = ["magmatic", "tests"]
reportUnnecessaryTypeIgnoreComment = "warning"
reportUnusedImport = "warning"
typeCheckingMode = "basic"

[tool.pytest.ini_options]
asyncio_mode = "strict"
