name: test

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8', '3.x' ]
    
    name: Testing ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -U -r requirements.txt
          pip install -U pytest
          pip install -U git+https://github.com/rapptz/discord.py

      - name: Run pytest
        run: |
          PYTHONPATH="$(pwd)" pytest
